DEBUG:
  console: true
  visualisation: false
  skip_ticks: false
  optimisation: false
  optimisation_individual : false
  debug_following : true
  
  #network dummies
  dummy_joystick_client: false

DEFAULTS:
  number_of_fish: 10
  zoa: 200
  zoo: 80
  zor: 10
  vision_angle: 300

  error_deg: 10
  max_speed: 10
  max_turn_rate: 150

  time_step: 0.05 #0.05 = 20fps

ARENA:
  width: 2000
  height: 2000
  repulsion: 150

NETWORK:
  position_port: 13000
  command_port: 13001
  joystick_port: 13002

ROBOT:
  controlled_from_start: false

ZONE_MODES:
  SMALL:
    zor: 10
    zoo: 50
    zoa: 200
  LARGE:
    zor: 20
    zoo: 100
    zoa: 300