DEBUG:
  console: false
  visualisation: True
  optimisation: false
  optimisation_individual : false
  
  #network dummies
  dummy_joystick_client: false

DEFAULTS:
  number_of_fish: 0
  zoa: 200
  zoo: 80
  zor: 10
  vision_angle: 300

  error_deg: 10
  max_speed: 10
  max_turn_rate: 200

  time_step: 0.05 #0.05 = 20fps

ARENA:
  width: 2000
  height: 2000
  repulsion: 150

WORLD:
  width: 64
  height: 64

NETWORK:
  position_port: 13000
  command_port: 13001
  joystick_port: 13002

CHARGER:
  position: [170, 1815]

ROBOT:
  controlled_from_start: false
  max_voltage: 90
  min_voltage: 50 
  charging_time: 10 #in minutes

ZONE_MODES:
  SMALL:
    zor: 40
    zoo: 300
    zoa: 300
  LARGE:
    zor: 40
    zoo: 60
    zoa: 100