DEBUG:
  console: false
  visualisation: True
  optimisation: false
  optimisation_individual : false
  debug_charging: false
  
  #network dummies
  #dummy_joystick_client: false

DEFAULTS:
  number_of_fish: 1
  zoa: 220
  zoo: 100
  zor: 40
  vision_angle: 300
  follow_angle: 90

  error_deg: 10
  max_speed: 6
  max_turn_rate: 200  #per second

  time_step: 0.05 #0.05 = 20fps
  heartbeat_path: E:/git_repos/robotracker/behavior_HF_dummy/heartbeat/RTLog.txt

ARENA:
  width: 2000
  height: 2000
  repulsion: 400

WORLD:
  width: 64
  height: 64

NETWORK:
  position_port: 13000
  command_port: 13001
  joystick_port: 13002
  charge_port: 13006
  robot_command_port: 13333
  robot_attribute_port: 13334

CHARGER:
  #position: [94, 1820]
  position: [1950,200]

ROBOT:
  controlled_from_start: false
  
  max_voltage: 8.5
  min_voltage: 7.4
  mean_voltage_full: 8.2
  charging_history_length: 10 #in minutes
  
  arena_repulsion: 300
  max_turn_rate: 800  #per second
  error_deg: 1

  zor: 1
  zoo: 50
  zoa: 500

ZONE_MODES:
  SMALL:
    zor: 40
    zoo: 300
    zoa: 300
  LARGE:
    zor: 40
    zoo: 60
    zoa: 100
  CHALL:
    zor: 40
    zoo: 100
    zoa: 220

LOGGING:
  #ROBOT: '/home/user1/RoboTracker_HF/logs/robot/robot'
  #ROBOT: '/home/hf-robofish/Desktop/robot'
  ROBOT: 'E:/git_repos/robotracker/behavior_HF_dummy/logs/robot/robot'
  INPUT: 'E:/git_repos/robotracker/behavior_HF_dummy/logs/user_input/user_input'
  FISH: 'E:/git_repos/robotracker/behavior_HF_dummy/logs/fish/fish'
  BEHAVIOR: 'E:/git_repos/robotracker/behavior_HF_dummy/logs/behavior_prints/behavior_prints'

SHUTDOWN:
  PATH: 'E:/git_repos/robotracker/behavior_HF_dummy/heartbeat/shutdown_trigger'
  CHARGING_PATH: 'E:/git_repos/robotracker/behavior_HF_dummy/heartbeat/shutdown_charging'
