DEBUG:
  console: false
  visualisation: true
  optimisation: false
  optimisation_individual : false
  debug_charging: false
  
  #network dummies
  #dummy_joystick_client: false

DEFAULTS:
  number_of_fish: 1
  zoa: 200
  zoo: 80
  zor: 10
  vision_angle: 300
  follow_angle: 90

  error_deg: 10
  max_speed: 10
  max_turn_rate: 200  #per second

  time_step: 0.05 #0.05 = 20fps

ARENA:
  width: 2000
  height: 2000
  repulsion: 300

WORLD:
  width: 64
  height: 64

NETWORK:
  position_port: 13000
  command_port: 13001
  joystick_port: 13002
  charge_port: 13006

CHARGER:
  position: [94, 1820]

ROBOT:
  controlled_from_start: false
  max_voltage: 8.4
  min_voltage: 7.5
  charging_time: 10 #in minutes
  arena_repulsion: 300
  max_turn_rate: 600  #per second
  error_deg: 1

ZONE_MODES:
  SMALL:
    zor: 40
    zoo: 300
    zoa: 300
  LARGE:
    zor: 40
    zoo: 60
    zoa: 100
  CHALL:
    zor: 40
    zoo: 100
    zoa: 220