DEBUG:
  console: true
  visualisation: false
  optimisation: false
  optimisation_individual : false
  debug_following : false
  
  #network dummies
  dummy_joystick_client: false

DEFAULTS:
  number_of_fish: 0
  zoa: 200
  zoo: 80
  zor: 10
  vision_angle: 300

  error_deg: 10
  max_speed: 10
  max_turn_rate: 200

  time_step: 0.05 #0.05 = 20fps

ARENA:
  width: 2000
  height: 2000
  repulsion: 150

WORLD:
  width: 64
  height: 64

NETWORK:
  position_port: 13000
  command_port: 13001
  joystick_port: 13002

CHARGER:
  position: [400, 1600]

ROBOT:
  controlled_from_start: true
  max_battery_charge: 90
  min_battery_charge: 50 

ZONE_MODES:
  SMALL:
    zor: 10
    zoo: 100
    zoa: 250
  LARGE:
    zor: 50
    zoo: 150
    zoa: 300